// <auto-generated />
using System;
using EFCoreExample.Infrastructure.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreExample.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EFCoreExample.Infrastructure.Domain.Models.Role", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00965ecf-acae-46fe-8775-d7834b07fd96"),
                            Abbreviation = "Stf",
                            Description = "People who work in school but not teaching",
                            Name = "Staff"
                        },
                        new
                        {
                            Id = new Guid("7ce68d5c-5b65-495a-8a63-14aeb48da87d"),
                            Abbreviation = "Fct",
                            Description = "People who teach in school",
                            Name = "Faculty"
                        },
                        new
                        {
                            Id = new Guid("1fb7085a-762f-440c-87de-59f75f85e935"),
                            Abbreviation = "Std",
                            Description = "People who learn in school",
                            Name = "Student"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
